### ISSUE TITLE
Sintesis Buenas prácticas en Gestión de Proyectos

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/actividad-3-sintesis-FedericoVictorianoSierra#2]

**Comment by FedericoVictorianoSierra** [comment]
[Sintesis (Federico Victoriano Sierra).pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-FedericoVictorianoSierra/files/12516293/Sintesis.Federico.Victoriano.Sierra.pdf)

**Comment by bg55-a** [comment]
calificacion: 20

**Comment by josealfredo79** [comment]
Bien hehcoy revisado..
